#!/system/bin/sh

/system/bin/setprop "net.interfaces.defaultroute" "cdma"
/system/bin/setprop "net.cdma.ppp.interface" "$IFNAME"
/system/bin/setprop "net.$IFNAME.local-ip" "$IPLOCAL"
/system/bin/setprop "net.$IFNAME.remote-ip" "$IPREMOTE"
/system/bin/setprop "net.$IFNAME.dns1" "$DNS1"
/system/bin/setprop "net.$IFNAME.dns2" "$DNS2"
/system/bin/setprop "ril.cdma.data_state" "2"
